### ISSUE TITLE
Not able to build gradle

### ISSUE THREAD

**Issue by saubhikde** [ngageoint/mage-android#25]
Error:(13, 0) Could not get unknown property 'Grgit' for object of type org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension.

**Comment by restjohn** [comment]
Can you add some more information, like OS, Gradle version, command line vs. IDE, etc?

Make sure you are using the [Gradle Wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html) to invoke the build, rather than your system's Gradle installation.  That is the `gradlew` script in the base project directory.
